### ISSUE TITLE
Josephus problem

### ISSUE THREAD

**Issue by Anshul727** [piyush-kash/HacktoberFest2022-kash#39]
Recursive solution for josephus problem

**Comment by Anshul727** [comment]
I can contribute to it

**Comment by agarwalson02** [comment]
I have submitted the solution for this problem (CPP section) . Kindly merge my PR.

**Comment by Utkarsh2312** [comment]
Hello,
I am a Competitive Programming Enthusiast. I would like to contribute in your repository. Can, you please assign this task to me.

**Comment by AdityaShaw1** [comment]
Pls assign me to this issue
